name: On Pull Request Update
on:
  pull_request:
    types:
      - opened
      - reopened
      - edited
      - synchronize

concurrency:
  group: ${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  unit-tests:
    name: "Unit Tests"
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Run unit tests
        run: npm test
        
      - name: Generate test coverage
        run: npm run test:coverage
        
      - uses: ArtiomTr/jest-coverage-report-action@v2
          
  e2e-tests:
    name: "E2E Tests" 
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Run e2e tests
        run: npm run test:e2e
        env:
          # Mock environment variables for testing
          APNS_KEY_FILE_BASE64: dGVzdC1rZXk=
          APNS_KEY_ID: test-key-id
          APNS_TEAM_ID: test-team-id
          APNS_BUNDLE_ID: test.bundle.id
          APNS_USE_PRODUCTION_ENDPOINT: "false"
          FIREBASE_SERVICE_ACCOUNT_JSON_BASE64: eyJ0eXBlIjogInNlcnZpY2VfYWNjb3VudCIsICJwcm9qZWN0X2lkIjogInRlc3QtcHJvamVjdCIsICJwcml2YXRlX2tleV9pZCI6ICJ0ZXN0LWtleS1pZCIsICJwcml2YXRlX2tleSI6ICItLS0tLUJFR0lOIFBSSVZBVEUgS0VZLS0tLS1cblRlc3QgS2V5XG4tLS0tLUVORCBQUklWQVRFIEtFWS0tLS0tXG4iLCAiY2xpZW50X2VtYWlsIjogInRlc3RAdGVzdC1wcm9qZWN0LmlhbS5nc2VydmljZWFjY291bnQuY29tIiwgImNsaWVudF9pZCI6ICIxMjM0NSIsICJhdXRoX3VyaSI6ICJodHRwczovL2FjY291bnRzLmdvb2dsZS5jb20vby9vYXV0aDIvYXV0aCIsICJ0b2tlbl91cmkiOiAiaHR0cHM6Ly9vYXV0aDIuZ29vZ2xlYXBpcy5jb20vdG9rZW4iLCAiYXV0aF9wcm92aWRlcl94NTA5X2NlcnRfdXJsIjogImh0dHBzOi8vd3d3Lmdvb2dsZWFwaXMuY29tL29hdXRoMi92MS9jZXJ0cyJ9

  build-docker:
    name: "Build"
    if: github.event.pull_request.user.login != 'dependabot[bot]'
    needs: [unit-tests, e2e-tests]
    uses: ./.github/workflows/callable-build-docker.yml
    secrets: inherit
    with:
      push: false
