name: On Pull Request Update
on:
  pull_request:
    types:
      - opened
      - reopened
      - edited
      - synchronize

concurrency:
  group: ${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  unit-tests:
    name: "Unit Tests"
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Run unit tests
        run: npm test

      - uses: ArtiomTr/jest-coverage-report-action@v2
        with:
          test-script: npm run test:coverage

  e2e-tests:
    name: "E2E Tests" 
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run e2e tests
        run: npm run test:e2e

  build-docker:
    name: "Build"
    if: github.event.pull_request.user.login != 'dependabot[bot]'
    needs: [unit-tests, e2e-tests]
    uses: ./.github/workflows/callable-build-docker.yml
    secrets: inherit
    with:
      push: false
